/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.ftchinese.api

import com.ftchinese.api.routes.contentRoutes
import io.ktor.server.engine.*
import io.ktor.server.netty.*

fun main() {
    embeddedServer(Netty, port = 8080) {
        contentRoutes()
    }.start(wait = true)
}
