/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.ftchinese.api

import com.ftchinese.api.dao.DatabaseFactory
import com.ftchinese.api.routes.contentRoutes
import io.ktor.serialization.kotlinx.json.*
import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import io.ktor.server.plugins.contentnegotiation.*
import kotlinx.serialization.json.Json

fun main() {
    embeddedServer(Netty, port = 8081) {
        install(ContentNegotiation) {
            json(Json {
                prettyPrint = true
                isLenient = true
                ignoreUnknownKeys = true
                encodeDefaults = true
            })
        }
        DatabaseFactory.init()
        contentRoutes()
    }.start(wait = true)
}
