/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example

import com.example.dao.DatabaseFactory
import com.example.plugins.*
import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*

fun main() {
    embeddedServer(Netty, port = 8081) {
        DatabaseFactory.init()
        webModule()
        apiModule()
    }.start(wait = true)
}

fun Application.webModule() {
    configureAuthRouting()
    configureArticleRouting()
}

fun Application.apiModule() {
    configureApiRouting()
    // Add plugin to specified module.
    configureSerialization()
}
