/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example

import com.example.dao.DatabaseFactory
import com.example.plugins.*
import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*

fun main() {
    embeddedServer(Netty, port = 8081) {
        DatabaseFactory.init()
        module1()
        module2()
        authModule()
    }.start(wait = true)
}

fun Application.module1() {
    configureWebRouting()
}

fun Application.module2() {
    configureApiRouting()
    // Add plugin to specified module.
    configureSerialization()
}

fun Application.authModule() {
    configureAuthRouting()
}
